version: '2.0'

services:
  express: #name of the first service
    build: 
      context: .
      dockerfile: ./docker/crypto.dockerfile
    ports: 
      - '8000:8000'
    links: 
      - database
    depends_on:
      - database
      
      
  database: #name of the second container
    image: mongo
    command: mongod
    ports: 
      - '27017:27017'